### ISSUE TITLE
Requesting for new effect

### ISSUE THREAD

**Issue by Thet-Tun-Aung** [jeffshee/NextGenVisualizer#1]
Sir, Please add circular beat bouncing with gradient effect. Thanks.

**Comment by jeffshee** [comment]
Hi. Thanks for your request 👍😊
Could you show me an example (a YouTube video will do) to clarify what kind of effect you mean by "circular beat bouncing with gradient"? A clear idea will make things easier to implement. 😀

**Comment by Thet-Tun-Aung** [comment]
I mean similar like that. Gradient and bouncing effect. Neon glow effect can be neglected. 😀 Thanks sir.

https://www.youtube.com/watch?v=esP3HWXwKm4

**Comment by jeffshee** [comment]
Hmm, while I didn't have time to show the demo on README, the `gradient` modifier is actually there. So adding a gradient color to the shape shouldn't be a problem.
The bouncing effect you mentioned could be achieved by using `beat` modifier as well.
I might do some example later if I got time 😃
![Screenshot_20190718-180648](https://user-images.githubusercontent.com/25530920/61444706-e4bfd600-a986-11e9-8214-783477e172f3.png)

**Comment by Thet-Tun-Aung** [comment]
Thanks for answering sir. 😊

![Screenshot_20190719-164156](https://user-images.githubusercontent.com/19220742/61528923-046a0380-aa46-11e9-87b7-8f5e87e2ee46.jpg)

I mean this effect with beating like below:
And then can be changed with adaptive color programmatically.
I mean combination of above and below effect. Just add beating to above.In new version , I can't add beating with image view in center.Thanks so much.

![2019_07_19_16_3-1563530791114](https://user-images.githubusercontent.com/19220742/61528363-8c4f0e00-aa44-11e9-8810-9959e80f8856.gif)

**Comment by jeffshee** [comment]
Hi
Yes, you can use `beat` and `blend` together, it depends how you put everything together. 
Here are some examples using the latest master build.

1. Example 1

![20190719_213120](https://user-images.githubusercontent.com/25530920/61535441-40fd2580-aa6d-11e9-9076-9e3a8c93d9ed.gif)
```kotlin
Beat(
    // Compose multiple Painters before pass it to Beat, this way you can add beat effect for all painters
    Compose(
        // Blend your shape with a gradient
        Blend(
            FftCLine().apply { paint.strokeWidth = 8f;paint.strokeCap = Paint.Cap.ROUND },
            Gradient(
                preset = Gradient.RADIAL,
                // You can change your color here, e.g. inner and outer color
                color1 = Color.rgb(153, 51, 255),
                color2 = Color.rgb(255, 0, 127)
            )
        ),
        // Your icon here
        Icon(circleBitmap)
    )
)
```

2. Example 2

![20190719_213314](https://user-images.githubusercontent.com/25530920/61535449-465a7000-aa6d-11e9-940a-fe6d56dc5dfa.gif)
```kotlin
Beat(
    Compose(
        Blend(
            Rotate(
                FftCWave(
                    startHz = 200, endHz = 1000, mirror = true, radiusR = .3f, ampR = .65f
                ).apply { paint.style = Paint.Style.STROKE; paint.strokeWidth = 4f }
                , rpm = 0f, offset = 90f
            ),
            Gradient(
                preset = Gradient.SWEEP,
                color1 = Color.rgb(153, 51, 255),
                color2 = Color.rgb(255, 0, 127)
            )
        ),
        Blend(
            Rotate(
                FftCWave(startHz = 200, endHz = 1200, mirror = true, radiusR = .3f),
                rpm = 0f, offset = 90f
            ),
            Gradient(
                preset = Gradient.SWEEP, hsv = true
            )
        ),
        Icon(circleBitmap)
     )
)
```
You will have to change the codes to match your usage.

**Comment by Thet-Tun-Aung** [comment]
Wow, awesome , thanks so much I'll try with new effects.  😊 😍
