### ISSUE TITLE
Requesting with neon glow effects

### ISSUE THREAD

**Issue by Thet-Tun-Aung** [jeffshee/NextGenVisualizer#4]
Sir, is it possible to make glow effects in visualizer? 😌

check in https://www.youtube.com/watch?v=9q7cO56NQTw

thanks 😊

**Comment by jeffshee** [comment]
Sorry for late replying, somehow I didn't get any notification from GitHub...
For Glow Effects, I had actually did some research, it seems that the only way to achieve it using the Android canvas API is to create a "blur" version below the actual drawing. See below:
https://stackoverflow.com/questions/30644816/how-to-add-glow-effect-on-custom-marker?rq=1

However, we can't do that operation under hardware acceleration (Android API limitation, see setMaskFilter section: https://developer.android.com/guide/topics/graphics/hardware-accel). That's mean we have to turn off the hardware acceleration (it hurts performance).

So, in brief, yep it's possible, and with some performance hit I believe. Sadly I don't have much time recently for this project tho. (You are welcome to fork it <3)

**Comment by Thet-Tun-Aung** [comment]
Thank you so much for your detail explanation sir. I'll try it. 😊
