### ISSUE TITLE
Update library

### ISSUE THREAD

**Issue by AdisAlagic** [jeffshee/NextGenVisualizer#7]
Could you please update your library and create aar/jitpack instance for quick install?

**Comment by jeffshee** [comment]
Hi @AdisAlagic ,
First of all, thanks for your interest in this project. At the moment, I'm afraid that I don't have much time for this project.
I will try my best, but I couldn't provide an ETA. If you want to use this library, I guess the quickest way is to clone this repo and use it in your code directly. Sorry about that. :-(

However, if you are an experienced Android developer and familiar with arr/jitpack, you are welcome to contribute to this project!
Please tell me if you want to become a collaborator. Collaboration is always welcome! ;-)

**Comment by AdisAlagic** [comment]
Unfortunately, i dont know kotlin to help, sorry.
